### ISSUE TITLE
Next major release features

### ISSUE THREAD

**Issue by panzer-punk** [cloudmediasolutions/Laravel-Scout-OpenSearch#5]
I've been working on extended sorting, and I have some thoughts about the next major release.

I think we need to make SearchFactory, ModelMapper and OpensearchBuilder as dependencies. It will give the user opportunity to change engine behavior on the fly.

For example, ModelMapper could be used as a model hydrator from _source to prevent additional calls to database.

OpensearchBuilder could be used as an extension of Scout/Builder to provide cursorPagination and other Opensearch specific features. Which user can bind through Provider.

I can write some code examples of how I see it. I think it will make this package more SOLID-like.

So, do you have plans on next releases?

**Comment by daannet** [comment]
@Gsuper36 I think the most important thing is what we do in this package. Laravel Scout itself is not very extensive than looking for models.

One of the current limitations is the outdated DSL package we are using now. I'm looking to see if an alternative, well-maintained package is available. If we would also bring this to this package, it would be a very large package to maintain...

The current DSL package is currently an issue for supporting Laravel 10 unfortunately... So it is important for the further development of this engine and our core products to solve this.

**Comment by panzer-punk** [comment]
@daannet I was thinking about DSL package, I've noticed it depends on elasticsearch client, so elasticsearch client is installed with DSL package. I think we could fork DSL package and make it compatible with both Opensearch and Elasticsearch. And then make this package dependable on our DSL fork.

**Comment by panzer-punk** [comment]
@daannet Maybe we should open issues for things like outdated DSL package. I'm going to add minor fixes for tests and then I'll make issues and PRs with my vision of this project's architecure.

**Comment by daannet** [comment]
@Gsuper36 There are a lot of issues and PRs, last commit on main branch was 5 Feb 2020.. So i don't expect anything of it.
